server:
  #端口
  port: 8886
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  # 时间格式化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  configuration:
    local-cache-scope: statement
    cache-enabled: true


swagger:
  j:
    single:
      title: J的接口文档
      description: J的starter创建的默认接口文档
      version: 1.1
      group-name: default
      base-package: cn.j.sbdemo.api1,cn.j.sbdemo.api2
      license: ...
      license-url: ....
      terms-of-service-url: ~~~~~~
    docket[0]:
      title: J的接口文档1
      description: J的starter创建的接口文档
      version: 1.2
      base-package: cn.j.sbdemo.api1
      group-name: 分组1
    docket[1]:
      title: J的接口文档2
      description: J的starter创建的接口文档
      version: 1.3
      base-package: cn.j.sbdemo.api2
      group-name: 分组2
