server:
  #端口
  port: 8886
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  # 时间格式化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
mybatis:
  mapper-locations: classpath:mapper-demo-db/*.xml