server:
  #端口
  port: 8886
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  # 时间格式化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
mybatis:
  mapper-locations: classpath:mapper-demo-db/*.xml

swagger:
  doc:
    docket[0]:
      title: J的接口文档0
      description: J的starter创建的
      version: 1.2
      base-package: cn.j.sbdemo.sys.api1
      group-name: 分组1
    docket[1]:
      title: J的接口文档1
      description: J的starter创建的
      version: 1.3
      base-package: cn.j.sbdemo.sys.api2
      group-name: 分组2
